### ISSUE TITLE
@guid not recognized

### ISSUE THREAD

**Issue by chris-hailstorm** [redwoodjs/tutorial#26]
PROBLEM

The tutorial gives an example of using GUIDs for DB primary keys instead of autoincrement.

The tutorial's recommended field declaration in `schema.prisma` is like this:

    id String @id @default(@guid)

Run `yarn redwood db save`, results in an "unexpected token" error. Tried this instead:

    id String @id @default(@guid())    // added "()"

Same error. Tried this instead:

    id String @id @default(guid())    // no "@", with "()"

Different error: "The function guid is not a known".

How do we declare a GUID field?

ENVIRONMENT

    $ yarn redwood --version
    0.0.1-alpha.30

**Comment by cannikin** [comment]
Sorry about that, that should have been `cuid` instead of `guid`! Also your second syntax example is correct, it should be a method call, not an `@` directive:

    uuid()
    cuid()

Here's the relevant section of the Prisma docs for this functionality: https://github.com/prisma/prisma2/blob/master/docs/data-modeling.md#ids

**Comment by cannikin** [comment]
Going to keep this open as a reminder to fix this in the tutorial.

**Comment by chris-hailstorm** [comment]
Sorry, slip of the mouse.

The `cuid` option is valuable, good thinking on that.
