### ISSUE TITLE
Update “First Commit” section to reflect git being run on installation bootstrap

### ISSUE THREAD

**Issue by thedavidprice** [redwoodjs/tutorial#34]
Section “Installation & Starting Development/First Commit”

Copy no longer applicable now that `yarn create…` handles git init and first commit. Maybe move content to after first `rw generate`. Also up for discussion per Rob’s preference to let user handle git setup and first commit+message.

<img width="684" alt="Screen Shot 2020-03-03 at 3 07 51 PM" src="https://user-images.githubusercontent.com/2951/75829444-0bd6e680-5d63-11ea-8763-76b65eb8b76c.png">

**Comment by cannikin** [comment]
I'd get @mojombo 's opinion on this: should we be doing the first commit (and writing the message) automatically for the user when they create a new redwood app? I vote "no" for a few reasons:

1. Redwood's shouldn't be involving itself in your version control process (other than including the default`.gitignore` file for convenience, rather than having to somehow tell you every file you should be excluding)
2. They might not be using `git`
3. The first commit message is kind of sacred for a brand new application and it sucks that their literal first interaction with Redwood is us taking away that choice

**Comment by mojombo** [comment]
Yeah, I'm with Rob on this one. I think it's an overstep to assume git and make the first commit. Sorry for not getting that opinion out before the code was merged to do it.

**Comment by thedavidprice** [comment]
Roger that and very simple revert — I’ll take care of it now. And will add “init git” instructions to the copy of suggested next steps in #114

I do disagree here if, though. This feels like a natural extension of “everything out of the box” you'll need upon bootstrap, and for those who don’t want it it’s easy to `rm -rf .git`. But I like the ethos behind “first commit being sacred”… Just for fun, ours is:
>Add aspirational README.

🚀
